name: zuhayr_uni_wien
description: "Demo Application"


version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.0
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.0
  flutter_screenutil: ^5.8.4
  google_fonts: ^5.1.0
  hooks_riverpod: ^2.3.6
  logger: ^1.4.0
  riverpod_annotation: ^2.1.1
  fluent_ui: ^4.8.7
  shared_preferences: 2.2.3 
  intl: 0.19.0
  go_router: ^10.0.0
  syncfusion_flutter_charts: ^26.1.39
  flutter_animate: ^4.5.0

dev_dependencies:
  ffigen: ^8.0.2
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.2.4
  riverpod_lint: ^2.3.10

flutter:
  generate: true
  uses-material-design: true

